name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run PHPCS
        run: vendor/bin/phpcs

      - name: Debug working directory
        run: |
          echo "PWD:"
          pwd
          echo "LIST:"
          ls -la
          echo "COMPOSER:"
          ls -la composer.json || true

