name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug repo structure
        run: |
          echo "ROOT:"
          pwd
          ls -la
          echo "SRC:"
          ls -la src || true
          echo "SRC composer.json:"
          ls -la src/composer.json || true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Install dependencies
        working-directory: src
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run PHPUnit
        working-directory: src
        run: vendor/bin/phpunit

      - name: Run PHPStan
        working-directory: src
        run: vendor/bin/phpstan analyse

      - name: Run PHPCS
        working-directory: src
        run: vendor/bin/phpcs
